export const FETCH_CATEGORY_SUCCESS = "FETCH_CATEGORY_SUCCESS";
export const SET_CATEGORY_INFO = "SET_CATEGORY_INFO";

export const SET_ARTICLE_INFO = "SET_ARTICLE_INFO";
export const SET_ARTICLE_LIST = "SET_ARTICLE_LIST";
